name: Context Pipeline

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Print Workflowname
        run: ${{github.workflow}}
      - name: Print User
        run: ${{github.actor}}
      - name: Print branch
        run: ${{github.ref_name}}
      - name: Print EVENT
        run: ${{github.event}}
      - name: Print SHA
        run: ${{github.sha}}
        
    