name: Demo Pipeline
on:
    pull_request:
        branches:
            -main
            -feature/**
permissions:
  id-token: write
  contents: read

jobs:
    plan-stage:
        runs-on: ubuntu-latest
        steps:
            #Checkout Code
            - name: Checkout Code
              uses: actions/checkout@v4
            #Setup for Terraform
            - name: Terraform Install
              uses: hashicorp/setup-terraform@v3
            #AZ Login using OIDC
            - name: Azure Login
              uses: azure/login@v3
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            #Terraform Workflow
            - name: Terraform Init
              run: terraform init
            - name: Terraform Formatting
              run: terraform fmt
            - name: Terraform Validation
              run: terraform validate
            - name: Terraform Plan
              run: terraform plan -out=tfplan
            #Upload Artifacts
            - name: Upload Terraform Plan
              uses: actions/upload-artifact@v4
              with:
                name: terraform-plan
                path: tfplan
    apply-stage:
        runs-on: ubuntu-latest
        steps:
            #Checkout Code
            - name: Checkout Code
              uses: actions/checkout@v4
            #Setup for Terraform
            - name: Terraform Install
              uses: hashicorp/setup-terraform@v3
            #AZ Login using OIDC
            - name: Azure Login
              uses: azure/login@v3
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            #Terraform Workflow
            - name: Terraform Init
              run: terraform init
            - name: Terraform Validation
              run: terraform validate
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                name: terraform-plan
                path: .
            - name: Terraform Apply
              run: terraform apply tfplan
