name: sample pipeline

on:
    push:

jobs:
    siddhant:
     runs-on: ubuntu-latest

     steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: read my name
          run: echo "Hello Siddhant"
