name: sample pipeline

on:
  workflow_dispatch:
  push:
env:
  NAME: Infosys

jobs:
  job1:
    env:
      BRANCH: Pune
    runs-on: ubuntu-latest
     
    
    steps:
      - name: Company's Name
        run: echo $NAME

      - name:
        run: echo $BRANCH
        
      - name:
        env:
          CITY: Nagpur
        run: echo $CITY
