name: practice Pipeline
on: 
  workflow_dispatch:
jobs:
  validate:
   runs-on: ubuntu-latest
   steps:
    - name: Validation stage
      run: echo "Inside Validation"
  plan:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Planning stage
        run: echo "Inside plan"
  apply:
    needs: plan
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Apply
        run: echo "Inside Apply"
      
    
